<?php

namespace App\Services;

use Config\Encryption;
use Config\Services;
use RuntimeException;
use Throwable;

class TelegramConfigurationService extends BaseService
{
    private const UNCONFIGURED_TOKEN = 'DISABLED_NOT_CONFIGURED';

    /** @return array<string, mixed> */
    public function settings(): array
    {
        $row = $this->rawSettings();
        $row['token_configured'] = $this->isConfiguredToken((string) $row['encrypted_bot_token']);
        unset($row['encrypted_bot_token']);
        $row['encryption_key_configured'] = $this->hasEncryptionKey();
        return $row;
    }

    /** @param array<string, mixed> $input @param array{ip:string,browser:string} $meta */
    public function save(array $input, string $actorId, array $meta): void
    {
        $old = $this->rawSettings();
        $data = [
            'bot_username' => $this->normalizeUsername((string) $input['bot_username']),
            'enabled' => ! empty($input['enabled']) ? 1 : 0,
            'notify_initial_assignment' => ! empty($input['notify_initial_assignment']) ? 1 : 0,
            'notify_routing' => ! empty($input['notify_routing']) ? 1 : 0,
            'notify_reassignment' => ! empty($input['notify_reassignment']) ? 1 : 0,
            'retry_attempts' => (int) $input['retry_attempts'],
            'updated_by' => $actorId,
            'updated_at' => date('Y-m-d H:i:s'),
        ];
        $token = trim((string) ($input['bot_token'] ?? ''));
        if (! empty($input['clear_token'])) {
            $data['encrypted_bot_token'] = self::UNCONFIGURED_TOKEN;
            $data['enabled'] = 0;
        } elseif ($token !== '') {
            if (! preg_match('/^\d{5,20}:[A-Za-z0-9_-]{20,}$/', $token)) {
                throw new RuntimeException('Telegram Bot Token format is invalid. Copy the token generated by BotFather and try again.');
            }
            $data['encrypted_bot_token'] = $this->encryptSecret($token);
        } elseif (! $this->isConfiguredToken((string) $old['encrypted_bot_token']) && $data['enabled'] === 1) {
            throw new RuntimeException('A Telegram Bot Token must be saved before the configuration can be enabled.');
        }

        $this->db->transBegin();
        try {
            if (! $this->db->table('telegram_settings')->where('telegram_setting_id', $old['telegram_setting_id'])->update($data)) {
                throw new RuntimeException('Telegram configuration could not be saved.');
            }
            $this->audit($actorId, 'UPDATE', 'Updated Telegram configuration', $this->auditSnapshot($old), $this->auditSnapshot($data + $old), $meta);
            $this->db->transCommit();
        } catch (Throwable $e) {
            $this->db->transRollback();
            throw $e;
        }
    }

    /** @param array{ip:string,browser:string} $meta @return array{username:string,name:string} */
    public function testBot(string $actorId, array $meta): array
    {
        $settings = $this->rawSettings();
        if (! $this->isConfiguredToken((string) $settings['encrypted_bot_token'])) {
            throw new RuntimeException('No Telegram Bot Token is configured. Save the BotFather token first.');
        }
        $token = $this->decryptSecret((string) $settings['encrypted_bot_token']);
        try {
            $client = Services::curlrequest(['timeout' => 8, 'connect_timeout' => 8, 'http_errors' => false], null, null, false);
            $response = $client->get('https://api.telegram.org/bot' . $token . '/getMe');
            $payload = json_decode((string) $response->getBody(), true);
        } catch (Throwable) {
            throw new RuntimeException('Could not reach the Telegram Bot API. Verify internet/TLS access from the iDocTrack server and try again.');
        }
        if ($response->getStatusCode() !== 200 || ! is_array($payload) || ($payload['ok'] ?? false) !== true || ! isset($payload['result']['username'])) {
            throw new RuntimeException('Telegram rejected the saved Bot Token. Generate/copy the current token from BotFather, save it, and try again.');
        }
        $username = '@' . ltrim((string) $payload['result']['username'], '@');
        $configured = $this->normalizeUsername((string) $settings['bot_username']);
        if (strcasecmp($username, $configured) !== 0) {
            throw new RuntimeException('The saved token belongs to ' . $username . ', but the configured Bot Username is ' . $configured . '. Correct the username and save again.');
        }
        $name = trim((string) (($payload['result']['first_name'] ?? '') . ' ' . ($payload['result']['last_name'] ?? '')));
        $result = ['username' => $username, 'name' => $name !== '' ? $name : $username];
        $this->audit($actorId, 'TEST', 'Verified Telegram bot connection', null, $result, $meta);
        return $result;
    }

    /** @return array<string, mixed> */
    private function rawSettings(): array
    {
        $row = $this->db->table('telegram_settings')->orderBy('updated_at', 'DESC')->get(1)->getRowArray();
        if ($row === null) {
            throw new RuntimeException('Telegram settings are missing. Run the admin/reference seeder once before configuring Telegram.');
        }
        return $row;
    }

    private function normalizeUsername(string $username): string
    {
        $username = trim($username);
        if ($username === '') {
            throw new RuntimeException('Telegram Bot Username is required.');
        }
        return '@' . ltrim($username, '@');
    }

    private function isConfiguredToken(string $value): bool
    {
        return $value !== '' && $value !== self::UNCONFIGURED_TOKEN;
    }

    private function hasEncryptionKey(): bool
    {
        return (string) config(Encryption::class)->key !== '';
    }

    private function encryptSecret(string $plainText): string
    {
        if (! $this->hasEncryptionKey()) {
            throw new RuntimeException('Bot Token was not saved because encryption.key is not configured. Run "php spark key:generate" once, then try again.');
        }
        return base64_encode(Services::encrypter()->encrypt($plainText));
    }

    private function decryptSecret(string $cipherText): string
    {
        if (! $this->hasEncryptionKey()) {
            throw new RuntimeException('The saved Bot Token cannot be decrypted because encryption.key is not configured.');
        }
        $decoded = base64_decode($cipherText, true);
        if ($decoded === false) {
            throw new RuntimeException('The saved Bot Token is not in the expected encrypted format. Save a new BotFather token.');
        }
        try {
            return (string) Services::encrypter()->decrypt($decoded);
        } catch (Throwable) {
            throw new RuntimeException('The saved Bot Token could not be decrypted with the current encryption key.');
        }
    }

    /** @param array<string, mixed> $row @return array<string, mixed> */
    private function auditSnapshot(array $row): array
    {
        return [
            'bot_username' => $row['bot_username'] ?? null,
            'token_configured' => isset($row['encrypted_bot_token']) && $this->isConfiguredToken((string) $row['encrypted_bot_token']),
            'enabled' => isset($row['enabled']) ? (int) $row['enabled'] : 0,
            'notify_initial_assignment' => isset($row['notify_initial_assignment']) ? (int) $row['notify_initial_assignment'] : 0,
            'notify_routing' => isset($row['notify_routing']) ? (int) $row['notify_routing'] : 0,
            'notify_reassignment' => isset($row['notify_reassignment']) ? (int) $row['notify_reassignment'] : 0,
            'retry_attempts' => isset($row['retry_attempts']) ? (int) $row['retry_attempts'] : null,
        ];
    }

    /** @param array<string, mixed>|null $old @param array<string, mixed>|null $new @param array{ip:string,browser:string} $meta */
    private function audit(string $actorId, string $action, string $description, ?array $old, ?array $new, array $meta): void
    {
        if (! $this->db->table('audit_logs')->insert([
            'user_id' => $actorId, 'document_id' => null, 'module_name' => 'Telegram Configuration', 'action_name' => $action,
            'description' => $description,
            'old_value' => $old === null ? null : json_encode($old, JSON_UNESCAPED_SLASHES),
            'new_value' => $new === null ? null : json_encode($new, JSON_UNESCAPED_SLASHES),
            'ip_address' => $meta['ip'] !== '' ? $meta['ip'] : null,
            'browser' => $meta['browser'] !== '' ? $meta['browser'] : null,
        ])) {
            throw new RuntimeException('The Telegram configuration audit record could not be saved.');
        }
    }
}
