<?= $this->extend('layouts/main') ?>

<?= $this->section('content') ?>
<section class="page-heading">
    <div class="eyebrow">ADMINISTRATION</div>
    <h1 class="page-title">Telegram Configuration</h1>
    <p class="lead compact">Configure the iDocTrack bot, notification events, and retry policy.</p>
</section>

<?php if ($loadError): ?><div class="alert alert-error"><?= esc($loadError) ?></div>
<?php else: ?>
<?php
$errors = session('errors') ?? [];
$value = static fn (string $name, string $fallback = ''): string => (string) old($name, $settings[$name] ?? $fallback, false);
$checked = static fn (string $name): bool => (string) old($name, (string) (int) ($settings[$name] ?? 0), false) === '1';
$enabled = $checked('enabled');
$tokenConfigured = (bool) $settings['token_configured'];
?>
<?php if ($errors): ?><div class="alert alert-error"><strong>Please review the form.</strong><ul><?php foreach ($errors as $error): ?><li><?= esc($error) ?></li><?php endforeach ?></ul></div><?php endif ?>
<div class="alert alert-info"><strong>Live notification channel:</strong> when enabled, iDocTrack uses this bot for the selected internal assignment/routing events after the workflow transaction commits. Use Test Bot Connection to verify the saved credential without sending a workflow message.</div>

<form class="settings-panel" action="<?= site_url('admin/telegram-settings') ?>" method="post" autocomplete="off">
    <?= csrf_field() ?>
    <section class="settings-section">
        <div class="service-status-card"><div><strong>Telegram Notification Service</strong><small>Controls internal notifications sent to explicitly assigned personnel with an enabled Telegram profile.</small></div><span id="telegramServiceBadge" class="badge <?= $enabled ? 'badge-success' : 'badge-muted' ?>"><?= $enabled ? 'Enabled' : 'Disabled' ?></span></div>
        <input type="hidden" name="enabled" value="0">
        <label class="settings-toggle"><span><strong>Enable Telegram Notification Configuration</strong><small>Turn off to keep the channel disabled without deleting its bot settings.</small></span><span class="toggle-control"><input id="telegramEnabled" type="checkbox" name="enabled" value="1" <?= $enabled ? 'checked' : '' ?>><span></span></span></label>
    </section>

    <section class="settings-section">
        <div class="settings-section-head"><h2>Telegram Bot</h2><p>Bot identity and protected API credential used by iDocTrack.</p></div>
        <div class="form-grid">
            <label class="field"><span>Bot Username *</span><input name="bot_username" maxlength="100" value="<?= esc($value('bot_username')) ?>" placeholder="@your_idoctrack_bot" required><small class="field-help">The leading @ is optional when entering the username.</small></label>
            <label class="field"><span>Retry Attempts *</span><input type="number" name="retry_attempts" min="0" max="10" value="<?= esc($value('retry_attempts', '3')) ?>" required></label>
            <label class="field field-wide"><span>Bot Token</span><input type="password" name="bot_token" maxlength="512" value="" autocomplete="new-password" placeholder="<?= $tokenConfigured ? 'Saved — leave blank to keep current token' : 'Paste the token generated by BotFather' ?>"><small class="field-help"><?= $tokenConfigured ? 'A protected token is stored. Enter a new one only to replace it.' : 'The token is a secret credential and will never be shown again by iDocTrack.' ?></small></label>
        </div>
        <?php if (! $settings['encryption_key_configured']): ?><div class="inline-notice warning"><strong>Encryption key not configured.</strong> Run <code>php spark key:generate</code> once before saving a Bot Token.</div><?php else: ?><div class="inline-notice success">Application encryption key is configured; new Bot Tokens will be encrypted before database storage.</div><?php endif ?>
        <div class="inline-notice telegram-help"><strong>Bot setup:</strong> create/manage the bot with <strong>@BotFather</strong> in Telegram and copy its generated token here. Treat that token like a password. <a href="https://core.telegram.org/bots/tutorial" target="_blank" rel="noopener noreferrer">Telegram bot setup guide ↗</a></div>
        <?php if ($tokenConfigured): ?><label class="compact-check"><input type="checkbox" name="clear_token" value="1"><span>Clear the saved Bot Token when configuration is saved (this also disables the Telegram channel)</span></label><?php endif ?>
    </section>

    <section class="settings-section">
        <div class="settings-section-head"><h2>Notification Events</h2><p>Choose which committed workflow events automatically notify the assigned personnel through Telegram.</p></div>
        <div class="settings-event-list">
            <input type="hidden" name="notify_initial_assignment" value="0">
            <label class="settings-toggle"><span><strong>Initial Assignment</strong><small>Notify the assigned recipient when a newly received document is assigned.</small></span><span class="toggle-control"><input type="checkbox" name="notify_initial_assignment" value="1" <?= $checked('notify_initial_assignment') ? 'checked' : '' ?>><span></span></span></label>
            <input type="hidden" name="notify_routing" value="0">
            <label class="settings-toggle"><span><strong>Document Routing</strong><small>Notify the next recipient when a document is routed.</small></span><span class="toggle-control"><input type="checkbox" name="notify_routing" value="1" <?= $checked('notify_routing') ? 'checked' : '' ?>><span></span></span></label>
            <input type="hidden" name="notify_reassignment" value="0">
            <label class="settings-toggle"><span><strong>Reassignment</strong><small>Notify the recipient when responsibility for a document is reassigned.</small></span><span class="toggle-control"><input type="checkbox" name="notify_reassignment" value="1" <?= $checked('notify_reassignment') ? 'checked' : '' ?>><span></span></span></label>
        </div>
    </section>

    <div class="settings-actions"><button class="button button-primary" type="submit">Save Configuration</button></div>
</form>

<form class="settings-test-action" action="<?= site_url('admin/telegram-settings/test') ?>" method="post" onsubmit="return confirm('Verify the currently SAVED Telegram Bot Token and username? This test does not send a message.');">
    <?= csrf_field() ?><div><strong>Bot Connection Test</strong><small>Save any changes above first. This calls Telegram getMe to verify the bot credential and username; no Telegram message is sent.</small></div><button class="button" type="submit">Test Bot Connection</button>
</form>

<script>
(function () {
    const enabled = document.getElementById('telegramEnabled');
    const badge = document.getElementById('telegramServiceBadge');
    enabled.addEventListener('change', () => {
        badge.textContent = enabled.checked ? 'Enabled' : 'Disabled';
        badge.className = 'badge ' + (enabled.checked ? 'badge-success' : 'badge-muted');
    });
}());
</script>
<?php endif ?>
<?= $this->endSection() ?>
