<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<?php
$plural = $type . 's';
$id = $record[$type . '_id'];
$code = $record[$type . '_code'];
$name = $record[$type . '_name'];
?>
<section class="page-heading page-heading-actions"><div><div class="eyebrow">ADMINISTRATION · ORGANIZATION · <?= esc(strtoupper($type)) ?></div><h1 class="page-title"><?= esc($name) ?></h1><p class="lead compact"><?= esc($code) ?></p></div><div class="heading-actions"><a class="button button-primary" href="<?= site_url('admin/organization/' . $plural . '/' . $id . '/edit') ?>">Edit <?= esc(ucfirst($type)) ?></a><?php if ($type === 'section'): ?><a class="button" href="<?= site_url('admin/organization/sections/' . $id . '/assignments') ?>">Assign Users</a><?php endif ?><form action="<?= site_url('admin/organization/' . $plural . '/' . $id . '/status') ?>" method="post" onsubmit="return confirm('<?= (int) $record['active'] === 1 ? 'Deactivate' : 'Activate' ?> this <?= esc($type) ?>?');"><?= csrf_field() ?><button class="button <?= (int) $record['active'] === 1 ? 'button-danger' : '' ?>" type="submit"><?= (int) $record['active'] === 1 ? 'Deactivate' : 'Activate' ?></button></form><a class="button" href="<?= site_url('admin/organization/' . $plural) ?>">Back to <?= esc(ucfirst($plural)) ?></a></div></section>
<section class="panel form-section"><div class="detail-header"><h2><?= esc(ucfirst($type)) ?> Details</h2><span class="badge <?= (int) $record['active'] === 1 ? 'badge-success' : 'badge-muted' ?>"><?= (int) $record['active'] === 1 ? 'Active' : 'Inactive' ?></span></div><dl class="definition-grid"><div><dt>Code</dt><dd><?= esc($code) ?></dd></div><div><dt>Name</dt><dd><?= esc($name) ?></dd></div><?php if ($type === 'office'): ?><div><dt>Departments</dt><dd><?= number_format((int) $record['department_count']) ?></dd></div><?php elseif ($type === 'department'): ?><div><dt>Parent Office</dt><dd><?= esc($record['office_code'] . ' — ' . $record['office_name']) ?></dd></div><div><dt>Sections</dt><dd><?= number_format((int) $record['section_count']) ?></dd></div><?php else: ?><div><dt>Office</dt><dd><?= esc($record['office_code'] . ' — ' . $record['office_name']) ?></dd></div><div><dt>Department</dt><dd><?= esc($record['department_code'] . ' — ' . $record['department_name']) ?></dd></div><div><dt>Section Head</dt><dd><?= esc($record['head_name'] ?: 'Not assigned') ?></dd></div><div><dt>Assigned Users</dt><dd><?= number_format((int) $record['user_count']) ?></dd></div><?php endif ?><div><dt>Created</dt><dd><?= esc($record['created_at']) ?></dd></div><div><dt>Updated</dt><dd><?= esc($record['updated_at'] ?: '—') ?></dd></div></dl></section>
<?= $this->endSection() ?>
